### ISSUE TITLE
Transfer repo

### ISSUE THREAD

**Issue by jess-shue** [jess-shue/soil_probe#13]
Hi @djkelly00  and @seanmcm ,
   Just adding an issue in regards to transferring the ownership of this repo to Sean or I. I think this site (scroll down the page) gives some steps to make this happen:  https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository

Thanks,
Jess

**Comment by djkelly00** [comment]
Thank you, @jess-shue! I'll take a look at this asap.

**Comment by jess-shue** [comment]
The transfer of the repository has been completed, so I'm closing this issue.
